set shell := ["cmd.exe", "/c"]

clear-venv:
    rm -r venv

build-venv:
    python -m venv venv
    pip install -r requirements.dev.txt

server:
    venv\Scripts\activate && python ./gateway/server.py


run:
    venv\Scripts\activate
